version: "3.8"

services:
  h-server-frontend:
    image: asia-northeast3-docker.pkg.dev/rus-web/rus-onprem/rus-h-server:${SERVER_IMAGE_TAG}
    restart: always
    ports:
      - 9000:9000
    environment:
      API_URL: https://${SERVER_IP}:${USER_PORT}/api
      IMAGE_DOMAIN: ${SERVER_IP}
      RELEASE_YEAR: 2023
      RELEASE_MONTH: 12
      RELEASE_DAY: 8
      RELEASE_VER: 1.1.0
      SERVICE_CODE: ${SERVICE_CODE}
      ENCRYPTION: ${ENCRYPTION}
      CHANGE_PASSWORD_CYCLE_DAYS: ${CHANGE_PASSWORD_CYCLE_DAYS}
      SURGERY_TYPE: ${SURGERY_TYPE}
      LANGUAGE: ${LANGUAGE}

  h-server-backend:
    image: asia-northeast3-docker.pkg.dev/rus-web/rus-onprem/h-server-backend:${SERVER_IMAGE_TAG}
    restart: always
    ports:
      - 9276:9276
    volumes:
      - ${STORAGE_PATH}:/usr/data
      - ${STORAGE_PATH}/dicom:/usr/data/dicom
      - ${STORAGE_PATH}/logs/user:/usr/logs
      - /etc/nginx/localCA/localhost.crt:/etc/ssl/localCA/localhost.crt
      - /etc/nginx/localCA/localhost.key:/etc/ssl/localCA/localhost.key
    environment:
      NODE_ENV: production
      SERVER_HOST: ${SERVER_IP}
      SERVER_PORT: "9276"
      SERVER_URL: https://${SERVER_IP}:${USER_PORT}/api
      REDIRECT_URL: https://${SERVER_IP}:${USER_PORT}
      ORIGIN_DOMAIN: ${SERVER_IP}
      APP_VERSION: ${SERVER_IMAGE_TAG}
      CLIENT_TZ: ${CLIENT_TZ}
      ENCRYPTION: ${ENCRYPTION}
      SEED_DATA: "off"
      DB_HOST: ${SERVER_IP}
      DB_PORT: "5432"
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      SECRET_KEY: ${SECRET_KEY}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SERVER_CODE: ${SERVER_CODE}
      SERVICE_CODE: ${SERVICE_CODE}
      LOG_PATH: /usr/logs
      STORAGE_PATH: /usr/data
      HUID_START_INDEX: ${HUID_START_INDEX}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      HCLOUD_SERVER_URL: ${PROXY_URL}
      SIGNED_CERT_PATH: /etc/ssl/localCA/localhost.crt
      SIGNED_KEY_PATH: /etc/ssl/localCA/localhost.key
      QR_SERVER_URL: http://${SERVER_IP}:8080
      QR_TIMEOUT_MS: 3600000
      QR_MAX_COUNT: 1
      PACS_SERVER_HOST: ${PACS_SERVER_HOST}
      PACS_SERVER_PORT: ${PACS_SERVER_PORT}
      PACS_SERVER_AET: ${PACS_SERVER_AET}
      CRON_STATUS: active
      CRON_SCHEDULE: ${CRON_SCHEDULE}
      CRON_LOG_SCHEDULE: ${CRON_LOG_SCHEDULE}
      CRON_DICOM_EXPIRED_DAYS: ${CRON_DICOM_EXPIRED_DAYS}
      CRON_NOTIFICATION_EXPIRED_DAYS: ${CRON_NOTIFICATION_EXPIRED_DAYS}
      CRON_SLEEP_USER_EXPIRED_DAYS: ${CRON_SLEEP_USER_EXPIRED_DAYS}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      DISK_FREE_SPACE: ${DISK_FREE_SPACE}
      SWAGGER_USER: hutom
      SWAGGER_PASSWORD: hutom13579!
      TZ: UTC

  scu:
    image: asia-northeast3-docker.pkg.dev/rus-web/h-dicom-server/scu:${SERVER_IMAGE_TAG}
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ${STORAGE_PATH}/logs/gunicorn:/usr/logs/gunicorn
      - ${STORAGE_PATH}/logs/scu:/usr/logs/scu
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_VERSION: ${SERVER_IMAGE_TAG}
      PORT: 8080
      AET: ${AET}
      LOG_DIR: /usr/logs/scu
      WORKERS: 1
      HDICOM_API_KEY: ${SERVER_CODE}

  scp:
    image: asia-northeast3-docker.pkg.dev/rus-web/h-dicom-server/scp:${SERVER_IMAGE_TAG}
    restart: always
    ports:
      - ${SCP_PORT}:1040
    volumes:
      - ${STORAGE_PATH}/dicom:/usr/data/dicom
      - ${STORAGE_PATH}/dicom/temp:/usr/data/dicom/temp
      - ${STORAGE_PATH}/logs/scp:/usr/logs/scp
    env_file:
      - .env
    environment:
      APP_ENV: production
      PORT: 1040
      AET: ${AET}
      PREFIX_HUID: ${SERVER_CODE}
      LOCAL_DIR: /usr/data/dicom
      REMOTE_DIR: /usr/data/dicom
      RUS_URL: http://${SERVER_IP}:9276
      ASSOCIATIONS: 1
      HDICOM_API_KEY: ${SERVER_CODE}
      LOG_DIR: /usr/logs/scp

  redis:
    image: asia-northeast3-docker.pkg.dev/rus-web/rus-onprem/h-server-redis:${SERVER_IMAGE_TAG}
    restart: always
    ports:
      - 6379:6379
