name: Build and Push

on:
  workflow_dispatch:
    inputs:
      name:
        description: "build and push on workflow_dispatch"
  push:
    tags:
      - "dev-*"
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set output
        id: set_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_KEY }}

      - name: Backend image build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test-gar/h-server-backend:${{ steps.set_tag.outputs.tag }}

      - name: Database(postgres) image build and push
        uses: docker/build-push-action@v3
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test-gar/h-server-database:${{ steps.set_tag.outputs.tag }}

      - name: Database(redis) image build and push
        uses: docker/build-push-action@v3
        with:
          context: ./database
          file: ./database/Dockerfile.redis
          push: true
          tags: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test-gar/h-server-redis:${{ steps.set_tag.outputs.tag }}

      - name: Nginx image build and push
        uses: docker/build-push-action@v3
        with:
          context: ./proxy
          file: ./proxy/Dockerfile
          push: true
          tags: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test-gar/h-server-nginx:${{ steps.set_tag.outputs.tag }}

      # - name: Slack notification
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{job.status}}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #     author_name: ${{ steps.set_tag.outputs.tag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
