name: Upload to Google Drive on Tag Push

on:
  push:
    tags:
      - "v*"

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [sto, kid] # 실행할 태그를 여기에 지정하세요.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: extract-tag
        run: |
          TAG_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $NF}')
          echo "Extracted tag name is: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Run generate-template.sh
        run: |
          chmod +x generate-template.sh
          ./generate-template.sh ${{ matrix.tag }} ${{ steps.extract-tag.outputs.tag_name }}

      - name: Upload a file to Google Drive
        # uses: willo32/google-drive-upload-action@v1
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          # target: ${{ github.workspace }}/h-server-setting-${{ matrix.tag }}-${{ steps.extract-tag.outputs.tag_name }}.zip
          # parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          filename: ${{ github.workspace }}/h-server-setting-${{ matrix.tag }}-${{ steps.extract-tag.outputs.tag_name }}.zip
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
