name: Create Docker Image Tarball by Retrieved Docker Images from GAR

on:
  push:
    tags:
      - "tar-test-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: extract-tag
        run: |
          TAG_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $NF}')
          echo "Extracted tag name is: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_KEY }}

      - name: Decode GCP Service Key
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}" | base64 --decode > keyfile.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=keyfile.json
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: List Docker images in GAR repository
        run: |
          # Remove trailing '/' from the image name
          IMAGE_NAME=$(echo "asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test-gar" | sed 's:/*$::')
          gcloud container images list-tags $IMAGE_NAME --format="value(tags)" > images.txt

      - name: Create Docker image tarball
        run: |
          while read -r image_tag; do
            docker pull $image_tag
          done
          docker save -o docker_images.tar $(cat images.txt | tr '\n' ' ')

      # - name: Upload a Directory with Mirror Directory Structure
      #   uses: adityak74/google-drive-upload-git-action@main
      #   with:
      #     credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
      #     filename: Release/${{ steps.extract-tag.outputs.tag_name }}/docker_images.tar
      #     folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      #     overwrite: "true"
      #     mirrorDirectoryStructure: "true"
