name: Update PR Labels

on:
  schedule:
    # - cron: "0 0 * * *" # 매 정각 0시마다 실행
    - cron: "10 * * * *" # 매 시 10분마다 실행

jobs:
  update-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          # Install GitHub CLI
          GITHUB_CLI_VERSION="2.0.0"  # 원하는 버전을 입력하세요.
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          URL="https://github.com/cli/cli/releases/download/v${GITHUB_CLI_VERSION}/gh_${GITHUB_CLI_VERSION}_${OS}_${ARCH}.tar.gz"
          curl -L "${URL}" | tar xz
          sudo mv gh_${GITHUB_CLI_VERSION}_${OS}_${ARCH}/gh /usr/local/bin/
          rm -rf gh_${GITHUB_CLI_VERSION}_${OS}_${ARCH}

      - name: Verify GitHub CLI installation
        run: gh --version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update PR Labels
        id: update-labels
        run: |
          for pr_number in $(gh pr list -s open -L 100 | awk '{print $1}'); do
            pr_labels=$(gh pr view $pr_number --json labels -q '.labels[].name' -R | jq -r '.[]')
            new_labels=$(echo "$pr_labels" | sed 's/D-5/D-4/g; s/D-4/D-3/g; s/D-3/D-2/g; s/D-2/D-1/g; s/D-1/D-0/g')
            gh pr edit $pr_number -L "$pr_labels" -L "$new_labels"
          done
