import { testRusCases } from "@root/seeding/seeder/seed/rus-case.seed";

export const testClinicalInfos = [
  {
    rusCaseId: testRusCases[0].id,
    operationType: "gastrectomy",
    deliveryDate: "20200101",
    age: 20,
    sex: "F",
    height: 160.5,
    weight: 50.2,
    childbirth: true,
  },
  {
    rusCaseId: testRusCases[1].id,
    operationType: "gastrectomy",
    deliveryDate: "20210102",
    age: 30,
    sex: "M",
    height: 170.21,
    weight: 60.21,
    childbirth: false,
  },
  {
    rusCaseId: testRusCases[2].id,
    operationType: "nephrectomy-left",
    deliveryDate: "20220103",
    age: 40,
    sex: "F",
    height: 165.23,
    weight: 50.32,
    childbirth: false,
  },
  {
    rusCaseId: testRusCases[3].id,
    operationType: "nephrectomy-right",
    deliveryDate: "20230104",
    age: 50,
    sex: "M",
    height: 175,
    weight: 70,
    childbirth: false,
  },
  {
    rusCaseId: testRusCases[4].id,
    operationType: "gastrectomy",
    deliveryDate: "20240104",
    age: 50,
    sex: "M",
    height: 175,
    weight: 70,
    childbirth: false,
  },
];
